wlanguage: perl

sudo: false

addons:
  apt:
    packages:
      - libffi-dev

install:
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | grep -v inc::Doco |cpanm -n
  - cpanm -n Exporter::Tidy
  - cpanm -n FFI::Platypus
  - cpanm -n Math::Int64
  - cpanm -n Pod::Abstract 
  - cpanm -n ExtUtils::CChecker Module::Build
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script: dzil test -v

env:
  global:
    - PERL_USE_UNSAFE_INC=0
